name: optiwindnet_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.11
  - absl-py>=2.0.0  # from ortools
  - bidict>=0.23.1
  - bitarray>=3.4.2
  - condeltri>=0.0.3
  - darkdetect>=0.8.0
  - esy.osm.pbf>=0.1.1
  - hybgensea>=0.0.1
  - immutabledict>=3.0.0  # from ortools
  - makefun>=1.15.6
  - matplotlib-base>=3.10.1
  - networkx>=3.6
  - numba>=0.62.1
  - numpy>=2.0
  - pandas>=2.0  # from ortools
  - peewee>=3.17
  - py>=1.11.0
  - pyomo>=6.9.5
  - pyyaml>=6.0.2
  - scipy>=1.15.2
  - shapely>=2.0.7
  - svg.py>=1.6.0
  - typing-extensions>=4.12  # from ortools
  - utm>=0.7.0
  - pip
  - pip:
      - ortools>=9.14
