name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch: # Keeps the manual execution button in the UI

jobs:
  fast-forward-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Natively via GitHub API
        run: gh repo sync ${{ github.repository }} --branch main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
